# Generated by Django 6.0.2 on 2026-03-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otpcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('donateur', 'Donateur'), ('beneficiaire', 'Bénéficiaire'), ('admin', 'Administrateur'), ('collectivite', 'Collectivité Locale'), ('food_saver', 'Food Saver'), ('user', 'Utilisateur Standard')], default='user', max_length=20),
        ),
    ]
