# Generated by Django 6.0.2 on 2026-04-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_reservation', 'New Reservation'), ('reservation_confirmed', 'Reservation Confirmed'), ('reservation_rejected', 'Reservation Rejected'), ('new_message', 'New Message'), ('nearby_donation', 'Nearby Donation'), ('urgent_donation', 'Urgent Donation'), ('nearby_user', 'Nearby User (Food Saver)')], max_length=50),
        ),
    ]
