# Generated by Django 6.0.2 on 2026-04-11 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0004_alter_reservation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('expired', 'Expired product posted as fresh'), ('dangerous', 'Dangerous or unsafe food'), ('misleading_desc', 'Misleading description'), ('inappropriate', 'Inappropriate content'), ('spam', 'Spam'), ('other', 'Other'), ('fake', 'Fake account'), ('misleading_info', 'Misleading information'), ('rude', 'Rude or Inappropriate behavior')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='report_screenshots/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('treated', 'Treated'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='donations.donation')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
