# Generated by Django 6.0.2 on 2026-04-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='action_taken',
            field=models.CharField(blank=True, choices=[('delete_post', 'Post Deleted'), ('deactivate_account', 'Account Deactivated'), ('send_warning', 'Warning Sent'), ('ignore', 'Ignored')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='treated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
