# Generated by Django 6.0.2 on 2026-05-26 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_email'),
        ('users', '0008_alter_user_email'),
    ]

    operations = [
    ]
