# Generated by Django 6.0.2 on 2026-03-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='category',
            field=models.CharField(choices=[('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('bread', 'Bread'), ('canned_goods', 'Canned Goods'), ('dairy', 'Dairy'), ('other', 'Other')], max_length=50),
        ),
    ]
