# Generated by Django 6.0.2 on 2026-03-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_donation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='urgency',
            field=models.CharField(choices=[('green', 'Fresh but not urgent'), ('orange', 'Dry or less perishable'), ('red', 'Urgent - pick up fast')], default='green', max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='confirmation_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='category',
            field=models.CharField(choices=[('fruits', 'Fruits'), ('legumes', 'Légumes'), ('pain', 'Pain'), ('conserves', 'Conserves'), ('produits_laitiers', 'Produits Laitiers'), ('autre', 'Autre')], max_length=50),
        ),
    ]
