# Generated by Django 6.0.2 on 2026-05-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_donation_updated_at_notinterested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='category',
            field=models.CharField(choices=[('Fruit', 'Fruit & Vegetables'), ('Pastries', 'Pastries'), ('Milk', 'Milk Products'), ('Meat', 'Meat & Fish'), ('Preserved', 'Preserved Food'), ('Cooked', 'Cooked Meals'), ('Drinks', 'Drinks'), ('Other', 'Other')], max_length=50),
        ),
    ]
