# Generated by Django 6.0.2 on 2026-05-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_migrate_category_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='quantity_confirmed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('donated', 'Donated'), ('expired', 'Expired'), ('deleted', 'Deleted')], default='active', max_length=20),
        ),
    ]
