# Generated by Django 6.0.2 on 2026-05-26 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_alter_donation_id_alter_notinterested_id_and_more'),
        ('donations', '0008_reservation_quantity_confirmed_alter_donation_status'),
    ]

    operations = [
    ]
