# Generated by Django 6.0.2 on 2026-05-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_alter_donation_id_alter_notinterested_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='available_quantity',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='pickup_address',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='title',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='urgency',
        ),
    ]
