# Generated by Django 6.0.2 on 2026-05-30 14:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_remove_donation_available_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='available_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donation',
            name='category',
            field=models.CharField(choices=[('Fruit', 'Fruit & Vegetables'), ('Pastries', 'Pastries'), ('Milk', 'Milk Products'), ('Meat', 'Meat & Fish'), ('Preserved', 'Preserved Food'), ('Cooked', 'Cooked Meals'), ('Drinks', 'Drinks'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='donation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='donation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='donations/'),
        ),
        migrations.AddField(
            model_name='donation',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='donation',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='donation',
            name='pickup_address',
            field=models.TextField(default='Not provided'),
        ),
        migrations.AddField(
            model_name='donation',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('donated', 'Donated'), ('expired', 'Expired'), ('deleted', 'Deleted')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='title',
            field=models.CharField(default='Untitled Donation', max_length=255),
        ),
        migrations.AddField(
            model_name='donation',
            name='unit',
            field=models.CharField(default='pieces', max_length=50),
        ),
        migrations.AddField(
            model_name='donation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='urgency',
            field=models.CharField(choices=[('green', 'Fresh but not urgent'), ('orange', 'Dry or less perishable'), ('red', 'Urgent - pick up fast')], default='green', max_length=10),
        ),
    ]
